# Generated by Django 4.2 on 2024-07-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachmentId', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=2000)),
                ('userId', models.CharField(max_length=20)),
                ('size', models.IntegerField()),
                ('url', models.CharField(max_length=2000)),
                ('mime', models.CharField(max_length=2000)),
                ('createdTime', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentId', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=2000)),
                ('userId', models.CharField(max_length=20)),
                ('issueId', models.CharField(max_length=20)),
                ('status', models.IntegerField()),
                ('iconUrl', models.IntegerField()),
                ('createdTime', models.IntegerField()),
                ('parentId', models.CharField(max_length=20)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HasIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueId', models.CharField(max_length=20)),
                ('parentId', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HasLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labelId', models.CharField(max_length=20)),
                ('parentId', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HasUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=20)),
                ('parentId', models.CharField(max_length=20)),
                ('roles', models.CharField(max_length=2000)),
                ('snoozedFromTime', models.IntegerField(blank=True, default=0)),
                ('snoozedToTime', models.IntegerField(blank=True, default=0)),
                ('isSnoozed', models.BooleanField(blank=True, default=False)),
                ('isArchived', models.BooleanField(blank=True, default=False)),
                ('inInbox', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueId', models.CharField(max_length=20)),
                ('start', models.IntegerField(blank=True, default=0)),
                ('end', models.IntegerField(blank=True, default=0)),
                ('parentId', models.CharField(blank=True, default='', max_length=20)),
                ('creatorId', models.CharField(max_length=20)),
                ('assigneeId', models.CharField(blank=True, default='', max_length=20)),
                ('reporterId', models.CharField(max_length=20)),
                ('summary', models.CharField(max_length=500)),
                ('summaryMd', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('descriptionMd', models.CharField(blank=True, default='', max_length=500)),
                ('projectId', models.CharField(blank=True, default='', max_length=20)),
                ('priorityId', models.CharField(blank=True, default='', max_length=20)),
                ('projectKey', models.CharField(blank=True, default='', max_length=500)),
                ('statusId', models.CharField(blank=True, default='', max_length=20)),
                ('typeId', models.CharField(blank=True, default='', max_length=20)),
                ('lastUpdateTime', models.IntegerField(blank=True, default=0)),
                ('createdTime', models.IntegerField(blank=True, default=0)),
                ('timeDone', models.IntegerField(blank=True, default=0)),
                ('timeTodo', models.IntegerField(blank=True, default=0)),
                ('extend', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labelId', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=2000)),
                ('parentId', models.CharField(max_length=20)),
                ('iconUrl', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='MemberInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberId', models.CharField(max_length=20)),
                ('fullName', models.CharField(max_length=2000)),
                ('account', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, default='', max_length=2000)),
                ('phoneNumber', models.CharField(blank=True, default='', max_length=10)),
                ('address', models.CharField(blank=True, default='', max_length=2000)),
                ('verified', models.BooleanField(blank=True, default=False)),
                ('dateOfBirth', models.CharField(blank=True, default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MemberRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField()),
                ('roleId', models.CharField(max_length=2000)),
                ('description', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priorityId', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=2000)),
                ('description', models.CharField(max_length=500)),
                ('color', models.CharField(max_length=2000)),
                ('type', models.IntegerField()),
                ('extends', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectId', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=2000)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('parentId', models.CharField(blank=True, default='', max_length=2000)),
                ('customerName', models.CharField(blank=True, default='', max_length=2000)),
                ('endTime', models.IntegerField(blank=True, default=0)),
                ('startTime', models.IntegerField(blank=True, default=0)),
                ('status', models.IntegerField(blank=True, default=1)),
                ('iconUrl', models.CharField(max_length=2000)),
                ('config', models.CharField(blank=True, default='', max_length=2000)),
                ('extend', models.CharField(default='', max_length=500, null=True)),
                ('key', models.CharField(blank=True, default=0, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusId', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=2000)),
                ('description', models.CharField(max_length=500)),
                ('flow', models.CharField(max_length=2000)),
            ],
        ),
    ]
