# Generated by Django 4.2 on 2024-07-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskup_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='createdTime',
            field=models.CharField(blank=True, default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='createdTime',
            field=models.CharField(blank=True, default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='iconUrl',
            field=models.CharField(blank=True, default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='hasuser',
            name='snoozedFromTime',
            field=models.CharField(blank=True, default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='hasuser',
            name='snoozedToTime',
            field=models.CharField(blank=True, default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='createdTime',
            field=models.CharField(blank=True, default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='end',
            field=models.CharField(blank=True, default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='lastUpdateTime',
            field=models.CharField(blank=True, default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='start',
            field=models.CharField(blank=True, default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='timeDone',
            field=models.CharField(blank=True, default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='timeTodo',
            field=models.CharField(blank=True, default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='memberrole',
            name='description',
            field=models.CharField(blank=True, default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='memberrole',
            name='role',
            field=models.CharField(blank=True, default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='memberrole',
            name='roleId',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='priority',
            name='extends',
            field=models.CharField(blank=True, default='0', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='endTime',
            field=models.CharField(blank=True, default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='extend',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='key',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='startTime',
            field=models.CharField(blank=True, default='0', max_length=20),
        ),
    ]
