# Generated by Django 4.2 on 2024-07-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskup_api', '0002_alter_attachment_createdtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHasProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=20)),
                ('projectId', models.CharField(max_length=20)),
                ('roles', models.CharField(max_length=2000)),
            ],
        ),
    ]
