# Generated by Django 4.2 on 2024-07-08 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskup_api', '0003_userhasproject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='IssueStatus',
        ),
    ]
