# Generated by Django 4.2 on 2024-07-08 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskup_api', '0004_rename_status_issuestatus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HasUser',
            new_name='IssueHasUser',
        ),
        migrations.RenameModel(
            old_name='HasIssue',
            new_name='ProjectHasIssue',
        ),
    ]
