# Generated by Django 4.2 on 2024-07-10 03:47

from django.db import migrations, models
import taskup_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('taskup_api', '0005_rename_hasuser_issuehasuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issueId',
            field=models.CharField(default=taskup_api.models.generate_random_user_id, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='memberId',
            field=models.CharField(default=taskup_api.models.generate_random_user_id, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=2000, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectId',
            field=models.CharField(default=taskup_api.models.generate_project_id, max_length=20, unique=True),
        ),
    ]
