# Generated by Django 4.2 on 2024-07-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskup_api', '0006_alter_issue_issueid_alter_memberinfo_memberid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=2000),
        ),
    ]
