# Generated by Django 4.2 on 2024-07-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskup_api', '0007_alter_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuestatus',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='issuestatus',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
