# Generated by Django 4.2 on 2024-07-11 15:18

from django.db import migrations, models
import taskup_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('taskup_api', '0008_issuestatus_name_alter_issuestatus_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issueId',
            field=models.CharField(default=taskup_api.models.generate_random_user_id, max_length=20),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='memberId',
            field=models.CharField(default=taskup_api.models.generate_random_user_id, max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectId',
            field=models.CharField(default=taskup_api.models.generate_project_id, max_length=20),
        ),
    ]
