# Generated by Django 4.2 on 2024-07-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskup_api', '0009_alter_issue_issueid_alter_memberinfo_memberid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuehasuser',
            name='inMyIssue',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='issuehasuser',
            name='inTodo',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='issuehasuser',
            name='lastseen',
            field=models.BooleanField(blank=True, default='0'),
        ),
    ]
