# Generated by Django 4.2 on 2024-07-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskup_api', '0011_alter_issuestatus_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='estimatePoint',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
