# Generated by Django 4.2 on 2024-07-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='account',
            field=models.CharField(default='', max_length=20),
        ),
    ]
